channels:
  - conda-forge
  - defaults
  - tpaviot

dependencies:
  - python>=3.9,<3.10
  - pythonocc-core==7.4.1 
  - fenics
  - pint 
  - intervaltree 
  - matplotlib 
  - pyyaml 
  - git 
  - spyder 
  - palettable 
  - openmdao
  - mshr
  - pip
  - pip:
    - shapely 
    - triangle 
    - quadpy
